### ISSUE TITLE
Can't get blink program from lab 0 to work

### ISSUE THREAD

**Issue by stkaplan** [dddrrreee/cs140e-20win#7]
I'm trying to follow the instructions for lab 0, and can't step 2 to work. I copied all the files to the SD card as instructed, but nothing happens from the Pi. I also tried `blink-actled.bin` as the kernel, and also nothing happens.

I installed Raspberry Pi OS on a separate SD card, and I can boot up into that. I can get an LED to blink using the Python GPIO library, so it shouldn't be a problem with my hardware or wiring. I also got part 1 working (powering an LED directly).

Has anyone gotten lab 0 to work? If so, can you post the contents of your SD card?

**Comment by stkaplan** [comment]
Found my problem - I was using a Raspberry Pi 3 A+ instead of the original A+. Model 3 has a different GPIO address: `0x3F000000` instead of `0x20000000`. It worked after changing the constants in `part2/blink-pin20.s` and rebuilding.

**Comment by dddrrreee** [comment]
yeah, sorry about not being clear about which pi.  will be changing that for this year!
